# Generated by Django 4.1 on 2023-05-09 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Media",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("page_place", models.CharField(max_length=50)),
                ("type", models.CharField(max_length=50)),
                ("url", models.CharField(max_length=150)),
                ("width", models.IntegerField()),
                ("height", models.IntegerField()),
                ("topleft_crop_x", models.IntegerField()),
                ("topleft_crop_y", models.IntegerField()),
                (
                    "event_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="events.event"
                    ),
                ),
            ],
        ),
    ]
