# Generated by Django 4.1.7 on 2023-03-21 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_categories_parent_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='parent_category',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='categories',
            name='resource_uri',
            field=models.URLField(blank=True, null=True),
        ),
    ]
