# Generated by Django 4.1 on 2023-05-02 16:57

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Discounts",
            fields=[
                (
                    "code",
                    models.CharField(
                        max_length=20, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("type", models.CharField(max_length=255)),
                ("end_date", models.DateTimeField()),
                ("start_date", models.DateTimeField()),
                ("percent_off", models.FloatField()),
                ("quantity_available", models.IntegerField()),
                ("quantity_sold", models.IntegerField()),
            ],
        ),
    ]
