# Generated by Django 4.1 on 2023-04-15 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("events", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Discounts",
            fields=[
                (
                    "code",
                    models.CharField(
                        max_length=20, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("type", models.CharField(max_length=255)),
                ("end_date", models.DateTimeField()),
                ("start_date", models.DateTimeField()),
                ("percent_off", models.FloatField()),
                ("quantity_available", models.IntegerField()),
                ("quantity_sold", models.IntegerField()),
                (
                    "event_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="events.event"
                    ),
                ),
            ],
        ),
    ]
