# Generated by Django 4.1.7 on 2023-03-22 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discounts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('type', models.CharField(max_length=255)),
                ('end_date', models.DateTimeField()),
                ('start_date', models.DateTimeField()),
                ('percent_off', models.FloatField()),
                ('quantity_available', models.IntegerField()),
                ('quantity_sold', models.IntegerField()),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
        ),
    ]
