# Generated by Django 4.1 on 2023-05-10 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("discounts", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discounts",
            name="quantity_sold",
            field=models.IntegerField(default=0),
        ),
    ]
