# Generated by Django 4.1 on 2023-04-15 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('promo_code', models.TextField(null=True)),
                ('status', models.CharField(choices=[('started', 'started'), ('pending', 'pending'), ('placed', 'placed'), ('abandoned', 'abandoned')], default='pending', max_length=16)),
                ('cost', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='events.event')),
            ],
        ),
    ]
