# Generated by Django 4.1 on 2023-04-06 17:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="event_id",
            new_name="event",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="user_id",
            new_name="user",
        ),
        migrations.AlterField(
            model_name="order",
            name="promo_code",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.TextField(blank=True),
        ),
    ]
