# Generated by Django 4.1 on 2023-05-02 16:57

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Attendees",
            fields=[
                ("attendee_id", models.AutoField(primary_key=True, serialize=False)),
                ("created", models.DateTimeField()),
                ("changed", models.DateTimeField()),
                ("quantity", models.IntegerField()),
                ("costs", models.FloatField()),
                ("checked_in", models.BooleanField()),
                ("cancelled", models.BooleanField()),
                ("refunded", models.BooleanField()),
                ("address", models.CharField(max_length=255)),
                ("delivery_method", models.CharField(max_length=255)),
                ("base_price", models.FloatField()),
                ("ticketwave_fee", models.FloatField()),
                ("tax", models.FloatField()),
                ("payment_fee", models.FloatField()),
                ("gross", models.FloatField()),
            ],
        ),
    ]
