# Generated by Django 4.1 on 2023-05-08 21:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Attendees",
            fields=[
                ("attendee_id", models.AutoField(primary_key=True, serialize=False)),
                ("created", models.DateTimeField()),
                ("changed", models.DateTimeField(blank=True)),
                ("quantity", models.IntegerField(blank=True)),
                ("costs", models.FloatField(blank=True)),
                ("checked_in", models.BooleanField()),
                ("cancelled", models.BooleanField()),
                ("refunded", models.BooleanField()),
                ("address", models.CharField(blank=True, max_length=255)),
                ("delivery_method", models.CharField(blank=True, max_length=255)),
                ("base_price", models.FloatField(blank=True)),
                ("ticketwave_fee", models.FloatField(blank=True)),
                ("tax", models.FloatField(blank=True)),
                ("payment_fee", models.FloatField(blank=True)),
                ("gross", models.FloatField(blank=True)),
                (
                    "user_id",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
