# Generated by Django 4.1 on 2023-05-10 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_remove_order_attendee_remove_order_first_name_and_more"),
        ("attendees", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendees",
            name="order_id",
            field=models.ForeignKey(
                default=-1,
                on_delete=django.db.models.deletion.CASCADE,
                to="orders.order",
            ),
            preserve_default=False,
        ),
    ]
