# Generated by Django 4.1 on 2023-05-09 11:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("summary", models.TextField(blank=True)),
                ("description", models.TextField(blank=True)),
                ("url", models.URLField(blank=True)),
                ("start", models.DateTimeField(blank=True, null=True)),
                ("end", models.DateTimeField(blank=True, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("changed", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "draft"),
                            ("live", "live"),
                            ("started", "started"),
                            ("ended", "ended"),
                            ("completed", "completed"),
                            ("canceled", "canceled"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("online_event", models.BooleanField(default=False)),
                ("hide_start_date", models.BooleanField(default=False)),
                ("hide_end_date", models.BooleanField(default=False)),
                ("free", models.BooleanField(default=False)),
                ("waitlist", models.BooleanField(default=False)),
                (
                    "view_counter",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("age_restriction", models.BooleanField(default=False)),
                ("fully_booked", models.BooleanField(default=False)),
                ("published", models.BooleanField(default=False)),
                ("organizer", models.CharField(max_length=80)),
                ("video_url", models.URLField(blank=True)),
                ("timezone", models.CharField(max_length=60)),
                ("language", models.CharField(max_length=60)),
                ("recurring", models.BooleanField(default=False)),
                (
                    "recurring_start_day",
                    models.CharField(
                        choices=[
                            ("monday", "monday"),
                            ("tuesday", "tuesday"),
                            ("wednesday", "wednesday"),
                            ("thursday", "thursday"),
                            ("friday", "friday"),
                            ("saturday", "saturday"),
                            ("sunday", "sunday"),
                        ],
                        default="saturday",
                        max_length=16,
                    ),
                ),
                (
                    "recurring_end_day",
                    models.CharField(
                        choices=[
                            ("monday", "monday"),
                            ("tuesday", "tuesday"),
                            ("wednesday", "wednesday"),
                            ("thursday", "thursday"),
                            ("friday", "friday"),
                            ("saturday", "saturday"),
                            ("sunday", "sunday"),
                        ],
                        default="saturday",
                        max_length=16,
                    ),
                ),
                (
                    "recurring_start_month",
                    models.CharField(
                        choices=[
                            ("january", "january"),
                            ("february", "february"),
                            ("march", "march"),
                            ("april", "april"),
                            ("may", "may"),
                            ("june", "june"),
                            ("july", "july"),
                            ("august", "august"),
                            ("september", "september"),
                            ("october", "october"),
                            ("november", "november"),
                            ("december", "december"),
                        ],
                        default="january",
                        max_length=16,
                    ),
                ),
                (
                    "recurring_end_month",
                    models.CharField(
                        choices=[
                            ("january", "january"),
                            ("february", "february"),
                            ("march", "march"),
                            ("april", "april"),
                            ("may", "may"),
                            ("june", "june"),
                            ("july", "july"),
                            ("august", "august"),
                            ("september", "september"),
                            ("october", "october"),
                            ("november", "november"),
                            ("december", "december"),
                        ],
                        default="january",
                        max_length=16,
                    ),
                ),
                ("recurring_start_year", models.PositiveIntegerField(default=2023)),
                ("recurring_end_year", models.PositiveIntegerField(default=2023)),
                (
                    "recurring_frequency",
                    models.CharField(
                        choices=[
                            ("daily", "daily"),
                            ("weekly", "weekly"),
                            ("monthly", "monthly"),
                            ("yearly", "yearly"),
                        ],
                        default="monthly",
                        max_length=16,
                    ),
                ),
                ("to_be_announced", models.BooleanField(default=False)),
                ("category", models.CharField(max_length=40)),
                ("type", models.CharField(max_length=40)),
                ("sub_category", models.CharField(blank=True, max_length=40)),
                ("listed", models.BooleanField(default=True)),
                ("shareable", models.BooleanField(default=True)),
                ("invite_only", models.BooleanField(default=False)),
                ("show_remaining", models.BooleanField(default=False)),
                ("password", models.TextField(blank=True, null=True)),
                ("capacity", models.IntegerField(default=50)),
                ("capacity_is_custom", models.BooleanField(default=False)),
            ],
        ),
    ]
