# Generated by Django 4.1.7 on 2023-03-21 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('summary', models.TextField()),
                ('description', models.TextField()),
                ('url', models.URLField()),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('changed', models.DateTimeField(auto_now=True)),
                ('status', models.TextField()),
                ('online_event', models.BooleanField()),
                ('hide_start_date', models.BooleanField()),
                ('hide_end_date', models.BooleanField()),
            ],
        ),
    ]
