# Generated by Django 4.1.7 on 2023-03-24 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('summary', models.TextField()),
                ('description', models.TextField()),
                ('url', models.URLField()),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('changed', models.DateTimeField(auto_now=True)),
                ('status', models.TextField()),
                ('online_event', models.BooleanField()),
                ('hide_start_date', models.BooleanField()),
                ('hide_end_date', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Event_private',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listed', models.BooleanField()),
                ('shareable', models.BooleanField()),
                ('invite_only', models.BooleanField()),
                ('show_remaining', models.BooleanField()),
                ('password', models.TextField()),
                ('capacity', models.IntegerField()),
                ('capacity_is_custom', models.BooleanField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
        ),
    ]
