# Generated by Django 4.1 on 2023-05-08 22:00

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Venue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("country", models.CharField(default="unknown", max_length=32)),
                ("state", models.CharField(default="unknown", max_length=32)),
                ("city", models.CharField(default="unknown", max_length=32)),
                ("address", models.CharField(default="unknown", max_length=120)),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
    ]
