# Generated by Django 4.1 on 2023-04-15 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('SalesStart', models.DateTimeField()),
                ('StartTime', models.DateTimeField()),
                ('SalesEnd', models.DateTimeField()),
                ('EndTime', models.DateTimeField()),
                ('CodeName', models.CharField(max_length=255)),
                ('RevealHidden', models.BooleanField()),
                ('Discount', models.FloatField()),
                ('PromoStart', models.DateTimeField()),
                ('PromoEnds', models.DateTimeField()),
                ('ApplyCode', models.BooleanField()),
                ('TicketLimit', models.SmallIntegerField()),
                ('CSVfile', models.FileField(upload_to='')),
                ('amount', models.PositiveIntegerField()),
                ('State', models.CharField(max_length=255)),
            ],
        ),
    ]
