# Generated by Django 4.1 on 2023-05-02 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("price", models.FloatField()),
                ("SalesStart", models.DateTimeField()),
                ("StartTime", models.DateTimeField()),
                ("SalesEnd", models.DateTimeField()),
                ("EndTime", models.DateTimeField()),
                ("CodeName", models.CharField(max_length=255)),
                ("RevealHidden", models.BooleanField()),
                ("Discount", models.FloatField()),
                ("PromoStart", models.DateTimeField()),
                ("PromoEnds", models.DateTimeField()),
                ("ApplyCode", models.BooleanField()),
                ("TicketLimit", models.SmallIntegerField()),
                ("amount", models.PositiveIntegerField()),
                ("State", models.CharField(max_length=255)),
                ("Capacity", models.IntegerField()),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="events.event"
                    ),
                ),
            ],
        ),
    ]
