# Generated by Django 4.1 on 2023-04-15 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='CSVfile',
        ),
        migrations.AddField(
            model_name='ticket',
            name='Capacity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
