# Generated by Django 4.1 on 2023-05-10 00:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="CodeName",
        ),
    ]
