from django.db import models
from django.contrib.auth.models import AbstractUser
from media.models import Media

class Users(AbstractUser):
<<<<<<< HEAD
  is_public = models.BooleanField(default=True)
  image_id = models.IntegerField()
=======
  #id, username, email, firstname, lastname are autogenerated
  is_public = models.BooleanField(default=True)
  image_id = models.IntegerField(default=-1) #models.ForeignKey(to= Media, on_delete=models.PROTECT, blank=True, null=True) 
  #can't be a foriegn key will lead to issues on user creation if image doesn't exist yet 
  
>>>>>>> 558759ba502ed9ddf266319e31f80f355bcd04ff
